### ISSUE TITLE
धर्मः -घासरः

### ISSUE THREAD

**Issue by chandrasekharanr** [sanskrit-lexicon/ApteES#8]
In the headword entry धर्मः [Cologne record ID=15976], there is a line in the _compound entries_ as below :

-घासरः the day of full moon. 

It should be -**वा**सरः the day of full moon. 

I had submitted this error through the "Corrections" form in the IIT-Koeln website.

What is the general turn around time for corrections? Just wanted to make sure someone is looking at this.

Thanks!

**Comment by drdhaval2785** [comment]
Generally turn around is a week or so. But this time it may take substantially longer.

**Comment by chandrasekharanr** [comment]
@drdhaval2785 , I can gladly help if needed.

**Comment by gasyoun** [comment]
> Just wanted to make sure someone is looking at this.

Sure, @funderburkjim is behind it.

> I can gladly help if needed.

There are lists of suspected words, would be great if you could go through them on a regular basis.

**Comment by funderburkjim** [comment]
> What is the general turn around time for corrections?

Dhaval's guesstimate of 1 week is low;  more like 1 month.

In general, I try to make a small reply email to correction form submissions, just so the submitter will know that the  correction has been attended to.

In the case of this -घासरः -> -वासरः  correction,  I'm mentioning it here since you opened this issue and the correction has been installed into AP90.

### kuca
You submitted another correction for ap90, namely that 'कुच  needs to be added to the list of Headwords'.  

In this case,  no 'correction' has been made.   The reason is that the AP90 headword is कुचः   (with the visarga).

Currently, displays for a given dictionary (e.g. AP90) generally use the headword spelling intrinsic to the dictionary.     However,  the  [simple-search](https://www.sanskrit-lexicon.uni-koeln.de/scans/awork/apidev/simple-search/v1.0/list-0.2s.html) displays, with input = *simple* irons out many of these minor differences among dictionaries.  For instance,  'kucaH' will be found in AP90 when the citation spelling is 'kuca':

![image](https://user-images.githubusercontent.com/6393033/52509367-d85c7380-2bc5-11e9-9ba3-395bf42cba66.png)

**Comment by funderburkjim** [comment]
### help with suspected words

These lists arise all along as we do one or another word study to improve the dictionaries. So there is no one place to look.  Generally,  investigations of such word lists go undone because no one has time.

@chandrasekharanr  : It would be good if this is something you might find interesting.   Just confirm your interest here, and I'llfind for you a couple of recent word lists that need review.

**Comment by chandrasekharanr** [comment]
> In the case of this -घासरः -> -वासरः correction, I'm mentioning it here since you opened this issue and the correction has been installed into AP90.

Thanks for the correction.

Also, thank you for the explanation for 'कुच', although I did not submit that change request!

**Comment by chandrasekharanr** [comment]
> 
> ### help with suspected words
> 
> These lists arise all along as we do one or another word study to improve the dictionaries. So there is no one place to look. Generally, investigations of such word lists go undone because no one has time.
> 
> @chandrasekharanr : It would be good if this is something you might find interesting. Just confirm your interest here, and I'llfind for you a couple of recent word lists that need review.

Yes, I am interested. Please let me know how I can help.

**Comment by chandrasekharanr** [comment]
@funderburkjim I am waiting for some assignment for me.

Thanks!

**Comment by drdhaval2785** [comment]
@chandrasekharanr Jim would not be available for some time. I will try and give you some task which may be of interest to you.

**Comment by chandrasekharanr** [comment]
@gasyoun just FYI, this issue of धर्मः -घासरः --> धर्मः -वासरः has been fixed. If you reopened the issue for any other reason, I suggest starting a new thread.
